[package]
name = "zg-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
clap.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
zg-engine = { path = "../zg-engine" }

[lints]
workspace = true
