version = "1.0"

[metadata]
benchmark = "peng-weihan/SWE-QA-Bench"
benchmark_revision = "c13deac7a0d99b0ca2e593e004c4739475785b08"
task_id = "pylint:10"
source_index = 10
index_base = 0
role = "category"
category = "what"
question_type = "what"
question_hash = "1aa04a329a1076648d7d51395128dc7b4e0fc9fd550f9c58d8ba0eaf8dda965f"
repository = "pylint-dev/pylint"
repository_commit = "44740e5e5cdd2b80321a4f0ed4254213d058b9f6"

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1200.0
