[package]
name = "zg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
serde_json.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing.workspace = true
tracing-subscriber.workspace = true
zg-cli = { path = "../zg-cli" }
zg-daemon = { path = "../zg-daemon" }
zg-daemon-protocol = { path = "../zg-daemon-protocol" }
zg-engine = { path = "../zg-engine" }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
