[package]
name = "zg-daemon-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
zg-engine = { path = "../zg-engine" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
