version = "1.0"

[metadata]
benchmark = "peng-weihan/SWE-QA-Bench"
benchmark_revision = "c13deac7a0d99b0ca2e593e004c4739475785b08"
task_id = "conan:1"
source_index = 1
index_base = 0
role = "category"
category = "what"
question_type = "what"
question_hash = "01b1b685c02cdde40aa9db7ed758bfb4c7b034eef69e72ccb66d32073965350f"
repository = "conan-io/conan"
repository_commit = "52f43d98fe44ab92d01317110488d0670c3e9e64"

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1200.0
