version = "1.0"

[metadata]
benchmark = "peng-weihan/SWE-QA-Bench"
benchmark_revision = "c13deac7a0d99b0ca2e593e004c4739475785b08"
task_id = "conan:19"
source_index = 19
index_base = 0
role = "category"
category = "how"
question_type = "how"
question_hash = "67fc4f56434dd3ba2a5f49a2fe639c47a6e7463db4007574f84e21989852154c"
repository = "conan-io/conan"
repository_commit = "52f43d98fe44ab92d01317110488d0670c3e9e64"

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1200.0
