export { createZvecGrep } from "./engine/service/index.js";
export type {
  CreateZvecGrepOptions,
  ZvecGrep,
  ZvecGrepContent,
  ZvecGrepContextWorkspaceIndex,
  ZvecGrepContextContainer,
  ZvecGrepContextCoverage,
  ZvecGrepContextDiagnostics,
  ZvecGrepContextFile,
  ZvecGrepContextGroupResult,
  ZvecGrepContextItem,
  ZvecGrepContextItemKind,
  ZvecGrepContextOptions,
  ZvecGrepContextResult,
  ZvecGrepGraphRelationship,
  ZvecGrepContextRoute,
  ZvecGrepContextSource,
  ZvecGrepStructureEnrichmentDiagnostics,
  ZvecGrepIndexDiagnostics,
  ZvecGrepInfoOptions,
  ZvecGrepInfoResult,
  ZvecGrepIndexOptions,
  ZvecGrepExploreOptions,
  ZvecGrepExploreResult,
  ZvecGrepGraphNeighborhoodOptions,
  ZvecGrepGraphNeighborhoodResult,
  ZvecGrepGraphDirection,
  ZvecGrepGraphEdge,
  ZvecGrepGraphEdgeKind,
  ZvecGrepGraphEntity,
  ZvecGrepGraphFile,
  ZvecGrepGraphNode,
  ZvecGrepGraphSeed,
  ZvecGrepGraphNeighbor,
  ZvecGrepExploreFileBundle,
  ZvecGrepRgDiagnostics,
  ZvecGrepSearchOptions,
} from "./engine/service/index.js";
export {
  createEmbeddingModel,
  EmbeddingPurpose,
} from "./engine/models/index.js";
export { isImageContent, isTextContent } from "./engine/types.js";
export type {
  CodeEntityMetadata,
  CodeEntityModifier,
  CodeSymbolType,
  WorkspaceIndexEmbeddingSchema,
  WorkspaceIndexPolicy,
  WorkspaceIndexStatus,
  WorkspaceIndexInfo,
  Content,
  ContentKind,
  EntityMetadata,
  FileScanDiagnostics,
  FileFormat,
  FileIndexStatus,
  FileInfo,
  FileKind,
  ImageContent,
  ImageFormat,
  IndexOptions,
  IndexProgress,
  IndexProgressPhase,
  IndexResult,
  MarkdownEntityMetadata,
  RootPath,
  SkippedFile,
  SkippedFileReason,
  SearchFinalTrace,
  SearchHitTrace,
  SearchRecallTrace,
  SearchStageTrace,
  TextContent,
  TimingEntry,
} from "./engine/types.js";
export type {
  CreateEmbeddingModelOptions,
  EmbeddingModel,
  EmbeddingModelProgress,
  EmbeddingModelInfo,
  EmbeddingOptions,
  EmbeddingResult,
} from "./engine/models/index.js";
