version = "1.0"

[metadata]
benchmark = "peng-weihan/SWE-QA-Bench"
benchmark_revision = "c13deac7a0d99b0ca2e593e004c4739475785b08"
task_id = "django:21"
source_index = 21
index_base = 0
role = "category"
category = "how"
question_type = "how"
question_hash = "98a8a7edabf45144b071d67015aff8f74fd8825278d14a876ddfaa9b76aa689c"
repository = "django/django"
repository_commit = "14fc2e97036fc9d7acb55ada4f16f1aa3bdc5ec7"

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 1800.0

[environment]
build_timeout_sec = 1200.0
