name: Security

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "43 4 * * 2"

permissions: {}

jobs:
  dependency-review:
    if: >-
      github.event_name == 'pull_request' &&
      (github.event.repository.visibility == 'public' || vars.ENABLE_GHAS == 'true')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: high

  codeql:
    if: >-
      github.event.repository.visibility == 'public' ||
      vars.ENABLE_GHAS == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: github/codeql-action/init@02c5e83432fe5497fd85b873b6c9f16a8578e1d9 # v3
        with:
          languages: javascript-typescript
      - uses: github/codeql-action/analyze@02c5e83432fe5497fd85b873b6c9f16a8578e1d9 # v3
